// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JFKW8IEfqPA_TfW-3QEQvpzuaQkXXw4',
    appId: '1:191560575751:web:feab261bfccc01dcc633a2',
    messagingSenderId: '191560575751',
    projectId: 'my-foodies-ab51b',
    authDomain: 'my-foodies-ab51b.firebaseapp.com',
    storageBucket: 'my-foodies-ab51b.firebasestorage.app',
    measurementId: 'G-KXD707FZY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxsdpoCmFZD8P5Iy-62UT0zZqIAqWj7Y',
    appId: '1:191560575751:android:b1454eeb665999fac633a2',
    messagingSenderId: '191560575751',
    projectId: 'my-foodies-ab51b',
    storageBucket: 'my-foodies-ab51b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBky_Q6m0GLJnI-i6bBAP3CWmde5f7nxE4',
    appId: '1:191560575751:ios:c0d3ae42b360b6f9c633a2',
    messagingSenderId: '191560575751',
    projectId: 'my-foodies-ab51b',
    storageBucket: 'my-foodies-ab51b.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );
}
